import {COLORS,SIZE,isShelf,toHex,fromHex,paintBits,thresholdPixels,worldToIso,isoToWorld,spotName,drawLabel} from './core.js';
const API='https://package-warehouse-api.ijsco123.chatgpt.site/api/packages';
const $=id=>document.getElementById(id),on=(id,event,fn)=>$(id).addEventListener(event,fn);
const emptyDraft=()=>({title:'',sender:'',recipient:'',message:'',color:COLORS[0],photo:null,caption:'',decorations:[]});
let draft=emptyDraft();try{const saved=JSON.parse(localStorage.getItem('package-draft-v1'));if(saved&&typeof saved.title==='string'&&Array.isArray(saved.decorations))draft={...draft,...saved};}catch{}
let pixels=fromHex(draft.photo),stickerBits=new Uint8Array(1024),hasPhoto=!!draft.photo,ink=1,stickerInk=1,history=[],selectedMark=-1,placing=false,selectedSpot=null,stream=null,sourcePixels=null,readerPackage=null,toastTimer;
const view={x:12,y:12,zoom:innerWidth<700?.83:1,level:0};
const canvas=$('warehouseCanvas'),ctx=canvas.getContext('2d');let width=0,height=0,parcels=new Map(),hitBoxes=[],needsRender=true,total=0,loading=false,online=false,loadTimer,loadController,loadSequence=0;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4500);}
function storeDraft(){draft.photo=hasPhoto?toHex(pixels):null;try{localStorage.setItem('package-draft-v1',JSON.stringify(draft));$('draftState').textContent='A draft is saved on this device.';}catch{$('draftState').textContent='Draft open here. Device storage is unavailable.';}}
function fieldUpdate(){for(const key of ['title','sender','recipient','message','caption'])draft[key]=$(key).value;$('messageCount').textContent=draft.message.length;storeDraft();renderEditor();}
for(const key of ['title','sender','recipient','message','caption']){$(key).value=draft[key];on(key,'input',fieldUpdate);}
COLORS.forEach((color,i)=>{const button=document.createElement('button');button.type='button';button.className='color';button.style.background=color;button.title=['Kraft paper','Dusty rose','Sage green','Golden oat','Blue slate','Muted plum'][i];button.setAttribute('aria-label',button.title);button.addEventListener('click',()=>{draft.color=color;storeDraft();renderEditor();});$('colors').append(button);});
function renderEditor(){drawLabel($('labelCanvas'),draft,selectedMark);document.querySelectorAll('.color').forEach((b,i)=>{b.classList.toggle('active',COLORS[i]===draft.color);b.setAttribute('aria-pressed',String(COLORS[i]===draft.color));});$('previewTitle').textContent=draft.title||'Your untitled parcel';$('previewFrom').textContent='From '+(draft.sender||'a stranger')+', with care.';drawPreview();$('photoStatus').textContent=hasPhoto?'Polaroid attached · 128 × 128 · black & white':'No Polaroid added yet.';$('messageCount').textContent=draft.message.length;}
function drawPreview(){const c=$('boxPreview').getContext('2d');c.clearRect(0,0,420,320);c.save();c.translate(210,180);c.fillStyle='#29261b15';c.beginPath();c.ellipse(0,76,133,35,0,0,Math.PI*2);c.fill();const poly=(points,color)=>{c.fillStyle=color;c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.fill();};poly([[-134,-38],[0,24],[0,112],[-134,48]],shade(draft.color,-23));poly([[0,24],[134,-38],[134,48],[0,112]],shade(draft.color,-42));poly([[-134,-38],[0,-101],[134,-38],[0,24]],draft.color);poly([[-15,-94],[-35,-85],[99,-23],[120,-32]],'#d9c39188');c.save();c.transform(.43,.20,-.43,.20,5,-69);drawLabel(labelThumb,draft);c.drawImage(labelThumb,0,0);c.restore();c.strokeStyle='#0002';c.lineWidth=1;c.beginPath();c.moveTo(-134,-38);c.lineTo(0,24);c.lineTo(134,-38);c.moveTo(0,24);c.lineTo(0,112);c.stroke();c.restore();}
const labelThumb=document.createElement('canvas');labelThumb.width=360;labelThumb.height=220;
function shade(hex,delta){const n=parseInt(hex.slice(1),16),f=v=>Math.max(0,Math.min(255,v+delta));return `rgb(${f(n>>16)},${f(n>>8&255)},${f(n&255)})`;}
function showTab(name){document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===name)));document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);if(name!=='photo')stopCamera();}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
function openComposer(){placing=false;$('placementBanner').hidden=true;$('placeCard').hidden=true;selectedSpot=null;needsRender=true;$('composer').showModal();renderEditor();}
on('createBtn','click',openComposer);on('closeComposer','click',()=>{$('composer').close();stopCamera();storeDraft();});$('composer').addEventListener('close',stopCamera);
on('packageForm','submit',e=>{e.preventDefault();fieldUpdate();if(!draft.title.trim()){showTab('wrap');$('title').focus();return;}if(!draft.message.trim()&&!hasPhoto){showTab('message');toast('Tuck in a message or a Polaroid first.');$('message').focus();return;}stopCamera();$('composer').close();placing=true;$('placementBanner').hidden=false;$('hint').textContent='Tap an empty shelf · Or use “Go to a spot”';needsRender=true;document.querySelector('.warehouse').scrollIntoView({behavior:'smooth',block:'start'});});
on('editDraft','click',openComposer);on('cancelPlace','click',()=>{placing=false;selectedSpot=null;$('placementBanner').hidden=true;$('placeCard').hidden=true;$('hint').textContent='Drag to wander · Tap a parcel to peek inside';needsRender=true;});
function addMark(type,text,bitmap){if(draft.decorations.length>=16){toast('This label fits up to 16 decorations. Remove one to add another.');return;}const n=draft.decorations.length;draft.decorations.push({type,text,x:230+(n%3)*22,y:110+(n%4)*19,rotation:-12+(n%3)*10,color:$('markColor').value,...(bitmap?{bitmap}:{})});selectedMark=draft.decorations.length-1;updateSelection();storeDraft();renderEditor();}
on('addStamp','click',()=>addMark('stamp',$('markText').value.trim()||'WITH LOVE'));on('addText','click',()=>addMark('text',$('markText').value.trim()||'HELLO'));['♥','★','✿','☀','↗','☾','!','☺'].forEach(text=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.setAttribute('aria-label','Add '+text+' sticker');b.onclick=()=>addMark('sticker',text);$('stickerChoices').append(b);});
function updateSelection(){const d=draft.decorations[selectedMark];$('rotation').value=d?.rotation||0;$('selectedMark').textContent=d?`Selected ${d.type}: ${d.text||'your drawing'}`:'Select a decoration on the label to move or rotate it.';}
on('rotation','input',()=>{if(selectedMark<0)return;draft.decorations[selectedMark].rotation=Number($('rotation').value);storeDraft();renderEditor();});on('deleteMark','click',()=>{if(selectedMark<0)return;draft.decorations.splice(selectedMark,1);selectedMark=-1;updateSelection();storeDraft();renderEditor();});
let markDrag=null;on('labelCanvas','pointerdown',e=>{const r=$('labelCanvas').getBoundingClientRect(),x=(e.clientX-r.left)*360/r.width,y=(e.clientY-r.top)*220/r.height;selectedMark=-1;for(let i=draft.decorations.length-1;i>=0;i--){const d=draft.decorations[i];if(Math.abs(d.x-x)<(d.type==='text'?55:40)&&Math.abs(d.y-y)<40){selectedMark=i;markDrag={dx:d.x-x,dy:d.y-y};break;}}$('labelCanvas').setPointerCapture(e.pointerId);updateSelection();renderEditor();});on('labelCanvas','pointermove',e=>{if(!markDrag||selectedMark<0)return;const r=$('labelCanvas').getBoundingClientRect(),d=draft.decorations[selectedMark];d.x=Math.max(25,Math.min(335,(e.clientX-r.left)*360/r.width+markDrag.dx));d.y=Math.max(25,Math.min(195,(e.clientY-r.top)*220/r.height+markDrag.dy));renderEditor();});for(const ev of ['pointerup','pointercancel'])on('labelCanvas',ev,()=>{markDrag=null;storeDraft();});
function bindDrawing(target,size,getBits,getInk,getBrush,before,after){let drawing=false,last=null;const point=e=>{const r=target.getBoundingClientRect();return {x:Math.min(size-1,Math.max(0,Math.floor((e.clientX-r.left)*size/r.width))),y:Math.min(size-1,Math.max(0,Math.floor((e.clientY-r.top)*size/r.height)))};};function stroke(p){const bits=getBits(),b=getBrush(),a=last||p,steps=Math.max(Math.abs(p.x-a.x),Math.abs(p.y-a.y),1);for(let step=0;step<=steps;step++){const x=Math.round(a.x+(p.x-a.x)*step/steps),y=Math.round(a.y+(p.y-a.y)*step/steps);for(let dy=-Math.floor(b/2);dy<Math.ceil(b/2);dy++)for(let dx=-Math.floor(b/2);dx<Math.ceil(b/2);dx++){const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<size&&ny<size)bits[ny*size+nx]=getInk();}}last=p;paintBits(target,bits,size);}
target.addEventListener('pointerdown',e=>{e.preventDefault();before();drawing=true;last=null;target.setPointerCapture(e.pointerId);stroke(point(e));});target.addEventListener('pointermove',e=>{if(drawing)stroke(point(e));});for(const ev of ['pointerup','pointercancel'])target.addEventListener(ev,()=>{if(!drawing)return;drawing=false;last=null;after();});}
function photoHistory(){history.push({bits:pixels.slice(),hasPhoto});if(history.length>20)history.shift();}
bindDrawing($('pixelCanvas'),128,()=>pixels,()=>ink,()=>Number($('brush').value),()=>{photoHistory();sourcePixels=null;$('convertTools').hidden=true;hasPhoto=true;},()=>{storeDraft();renderEditor();});
bindDrawing($('stickerCanvas'),32,()=>stickerBits,()=>stickerInk,()=>1,()=>{},()=>{});
on('inkBtn','click',()=>{ink=1;$('inkBtn').classList.add('active');$('eraseBtn').classList.remove('active');});on('eraseBtn','click',()=>{ink=0;$('inkBtn').classList.remove('active');$('eraseBtn').classList.add('active');});on('stickerErase','click',()=>{stickerInk=1-stickerInk;$('stickerErase').textContent=stickerInk?'Ink / erase':'Erasing / ink';});on('clearSticker','click',()=>{stickerBits.fill(0);paintBits($('stickerCanvas'),stickerBits,32);});on('addDrawing','click',()=>{if(!stickerBits.some(Boolean)){toast('Draw a little sticker first.');return;}addMark('drawing','HANDMADE',toHex(stickerBits));});
on('undoPhoto','click',()=>{const old=history.pop();if(!old)return;pixels=old.bits;hasPhoto=old.hasPhoto;sourcePixels=null;$('convertTools').hidden=true;paintBits($('pixelCanvas'),pixels,128);storeDraft();renderEditor();});on('clearPhoto','click',()=>{photoHistory();pixels.fill(0);hasPhoto=true;sourcePixels=null;$('convertTools').hidden=true;paintBits($('pixelCanvas'),pixels,128);storeDraft();renderEditor();});on('removePhoto','click',()=>{photoHistory();pixels.fill(0);hasPhoto=false;sourcePixels=null;$('convertTools').hidden=true;paintBits($('pixelCanvas'),pixels,128);storeDraft();renderEditor();});on('drawMode','click',()=>{stopCamera();sourcePixels=null;$('convertTools').hidden=true;});
on('uploadBtn','click',()=>$('fileInput').click());on('cameraBtn','click',async()=>{if(!navigator.mediaDevices?.getUserMedia){$('cameraInput').click();return;}try{stopCamera();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:640},height:{ideal:640}},audio:false});$('cameraVideo').srcObject=stream;$('cameraPanel').hidden=false;}catch{toast('Use the camera or choose a photo on your device.');$('cameraInput').click();}});
function stopCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;$('cameraVideo').srcObject=null;$('cameraPanel').hidden=true;}
on('stopCamera','click',stopCamera);on('captureBtn','click',()=>{const v=$('cameraVideo');if(!v.videoWidth){toast('The camera is still starting. Try again in a moment.');return;}importImage(v,v.videoWidth,v.videoHeight);stopCamera();});
for(const id of ['fileInput','cameraInput'])on(id,'change',async()=>{const file=$(id).files[0];if(!file)return;if(file.size>20000000){toast('Choose an image smaller than 20 MB.');return;}try{const bitmap=await createImageBitmap(file);importImage(bitmap,bitmap.width,bitmap.height);bitmap.close();}catch{toast('Could not read that image. Try a JPEG or PNG.');}$(id).value='';});
function importImage(image,w,h){photoHistory();const off=document.createElement('canvas');off.width=off.height=128;const c=off.getContext('2d'),s=Math.min(w,h);c.fillStyle='#fff';c.fillRect(0,0,128,128);c.drawImage(image,(w-s)/2,(h-s)/2,s,s,0,0,128,128);sourcePixels=c.getImageData(0,0,128,128).data;hasPhoto=true;$('convertTools').hidden=false;convertPhoto();}
function convertPhoto(){if(!sourcePixels)return;pixels=thresholdPixels(sourcePixels,128,Number($('threshold').value),$('dither').checked);paintBits($('pixelCanvas'),pixels,128);storeDraft();renderEditor();}on('threshold','input',convertPhoto);on('dither','change',convertPhoto);
function resize(){const r=canvas.getBoundingClientRect();width=r.width;height=r.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);needsRender=true;scheduleLoad();}new ResizeObserver(resize).observe(canvas);
function project(x,y){const p=worldToIso(x-view.x,y-view.y);return {x:width/2+p.x*view.zoom,y:height/2+p.y*view.zoom};}
function unproject(sx,sy){const p=isoToWorld((sx-width/2)/view.zoom,(sy-height/2)/view.zoom);return {x:p.x+view.x,y:p.y+view.y};}
function poly(points,fill,stroke){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.65;ctx.stroke();}}
function renderWarehouse(){ctx.clearRect(0,0,width,height);ctx.fillStyle='#dfddcf';ctx.fillRect(0,0,width,height);hitBoxes=[];const corners=[unproject(0,0),unproject(width,0),unproject(0,height),unproject(width,height)];const minX=Math.max(0,Math.floor(Math.min(...corners.map(p=>p.x)))-2),maxX=Math.min(239,Math.ceil(Math.max(...corners.map(p=>p.x)))+2),minY=Math.max(0,Math.floor(Math.min(...corners.map(p=>p.y)))-2),maxY=Math.min(239,Math.ceil(Math.max(...corners.map(p=>p.y)))+2);ctx.save();const v=worldToIso(view.x,view.y);ctx.translate(width/2-v.x*view.zoom,height/2-v.y*view.zoom);ctx.scale(view.zoom,view.zoom);const cells=[];for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++)cells.push({x,y});cells.sort((a,b)=>a.x+a.y-b.x-b.y||a.x-b.x);
for(const cell of cells){const {x,y}=cell,p=worldToIso(x,y),sx=p.x,sy=p.y;const shelf=isShelf(x,y);const selected=selectedSpot&&selectedSpot.x===x&&selectedSpot.y===y;
poly([[sx,sy-16],[sx+32,sy],[sx,sy+16],[sx-32,sy]],shelf?'#e4e1d4':'#d4d3c4','#cdcbbc');if(!shelf){if((x%6===5&&y%8===3)||(y%8===7&&x%6===2)){ctx.save();ctx.translate(sx,sy);ctx.rotate(-Math.PI/6);ctx.fillStyle='#999b89';ctx.font='8px monospace';ctx.textAlign='center';ctx.fillText(x%6===5?'AISLE '+String(x+1).padStart(3,'0'):'BAY '+String(y+1).padStart(3,'0'),0,0);ctx.restore();}continue;}
const parcel=parcels.get(`${x},${y}`);if(parcel){drawBox(sx,sy,parcel);const pos=project(x,y);hitBoxes.push({x:pos.x,y:pos.y-22*view.zoom,parcel});}else{poly([[sx-25,sy],[sx,sy+12],[sx+25,sy],[sx+25,sy+5],[sx,sy+17],[sx-25,sy+5]],'#9b9d8f');poly([[sx,sy-12],[sx+25,sy],[sx,sy+12],[sx-25,sy]],selected?'#efd268':placing?'#e6e2cc':'#cacbbb','#adb1a0');ctx.strokeStyle='#8f9485';ctx.lineWidth=1.1;ctx.beginPath();ctx.moveTo(sx-23,sy-1);ctx.lineTo(sx-23,sy-6);ctx.moveTo(sx+23,sy-1);ctx.lineTo(sx+23,sy-6);ctx.stroke();if(selected){ctx.fillStyle='#655927';ctx.font='16px monospace';ctx.textAlign='center';ctx.fillText('+',sx,sy+5);}}}
ctx.restore();const vignette=ctx.createRadialGradient(width/2,height/2,Math.min(width,height)*.2,width/2,height/2,Math.max(width,height)*.65);vignette.addColorStop(0,'#8b897800');vignette.addColorStop(1,'#8b897816');ctx.fillStyle=vignette;ctx.fillRect(0,0,width,height);$('coords').textContent=`AISLE ${String(Math.round(view.x)+1).padStart(3,'0')} / BAY ${String(Math.round(view.y)+1).padStart(3,'0')}`;$('zone').textContent=`SECTOR ${String.fromCharCode(65+Math.floor(view.x/24))}${Math.floor(view.y/24)+1}`;}
function drawBox(x,y,p){const h=26+(p.title.length%3)*4;poly([[x-26,y+3],[x,y+16],[x+26,y+3],[x+26,y+8],[x,y+21],[x-26,y+8]],'#44443522');poly([[x-25,y-h],[x,y-h+12],[x,y+12],[x-25,y]],shade(p.color,-24),'#6b563144');poly([[x,y-h+12],[x+25,y-h],[x+25,y],[x,y+12]],shade(p.color,-44),'#6b563144');poly([[x,y-h-12],[x+25,y-h],[x,y-h+12],[x-25,y-h]],p.color,'#6b563144');poly([[x-4,y-h-10],[x+1,y-h-12],[x+25,y-h],[x+20,y-h+2]],'#dfc699a0');ctx.save();ctx.transform(.058,.029,-.058,.029,x-1,y-h-8);const key=p.id;if(!labelCache.has(key)){const c=document.createElement('canvas');c.width=360;c.height=220;drawLabel(c,p);labelCache.set(key,c);if(labelCache.size>400)labelCache.delete(labelCache.keys().next().value);}ctx.drawImage(labelCache.get(key),0,0);ctx.restore();}
const labelCache=new Map();function frame(){if(needsRender){renderWarehouse();needsRender=false;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
function bounds(){const p=unproject(width/2,height/2);return {x:Math.max(0,Math.min(180,Math.floor(p.x)-30)),y:Math.max(0,Math.min(180,Math.floor(p.y)-30)),w:60,h:60,level:view.level};}
function scheduleLoad(){clearTimeout(loadTimer);loadTimer=setTimeout(loadPackages,250);}
async function loadPackages(){const seq=++loadSequence;loadController?.abort();loadController=new AbortController();const controller=loadController;const timer=setTimeout(()=>controller.abort(),12000);loading=true;const b=bounds();try{const r=await fetch(API+'?'+new URLSearchParams(b),{signal:loadController.signal});if(!r.ok)throw new Error('Unavailable');const data=await r.json();if(seq!==loadSequence)return;parcels=new Map(data.packages.map(p=>[`${p.x},${p.y}`,p]));total=data.total;online=true;$('count').textContent=total+' parcel'+(total===1?'':'s')+' left';$('statusDot').classList.remove('offline');$('viewCount').textContent=data.packages.length;needsRender=true;renderList();const link=new URLSearchParams(location.search);if(link.has('p')&&!readerPackage){const p=data.packages.find(p=>p.id===link.get('p'));if(p)openPackage(p);else{toast('That package could not be found at these coordinates.');historyReplace();}}}catch(e){if(seq!==loadSequence)return;if(e.name==='AbortError')return;online=false;$('statusDot').classList.add('offline');$('count').textContent='Connection paused';toast('The warehouse connection is unavailable. Your draft stays on this device.');}finally{clearTimeout(timer);if(seq===loadSequence)loading=false;}}
const pointers=new Map();let dragStart=null,lastPan=null,pinchStart=null,moved=false;
on('warehouseCanvas','pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});if(pointers.size===1){dragStart={x:e.offsetX,y:e.offsetY};lastPan={...dragStart};moved=false;}if(pointers.size===2){const [a,b]=[...pointers.values()];pinchStart={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:view.zoom};moved=true;}});
on('warehouseCanvas','pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});if(pointers.size>=2){const[a,b]=[...pointers.values()];if(pinchStart)view.zoom=Math.max(.7,Math.min(1.8,pinchStart.zoom*Math.hypot(a.x-b.x,a.y-b.y)/pinchStart.distance));needsRender=true;return;}if(!lastPan)return;const dx=e.offsetX-lastPan.x,dy=e.offsetY-lastPan.y;if(Math.hypot(e.offsetX-dragStart.x,e.offsetY-dragStart.y)>7)moved=true;const d=isoToWorld(dx/view.zoom,dy/view.zoom);view.x=Math.max(0,Math.min(239,view.x-d.x));view.y=Math.max(0,Math.min(239,view.y-d.y));lastPan={x:e.offsetX,y:e.offsetY};needsRender=true;scheduleLoad();});
on('warehouseCanvas','pointerup',e=>{pointers.delete(e.pointerId);if(!moved&&dragStart)handleTap(e.offsetX,e.offsetY);lastPan=null;pinchStart=null;if(pointers.size===1){const p=[...pointers.values()][0];lastPan={...p};dragStart={...p};}scheduleLoad();});on('warehouseCanvas','pointercancel',e=>{pointers.delete(e.pointerId);lastPan=null;pinchStart=null;moved=true;});
on('warehouseCanvas','wheel',e=>{e.preventDefault();view.zoom=Math.max(.7,Math.min(1.8,view.zoom*Math.exp(-e.deltaY*.001)));needsRender=true;scheduleLoad();});
function handleTap(sx,sy){const hit=[...hitBoxes].reverse().find(h=>Math.abs(h.x-sx)+Math.abs(h.y-sy)*1.7<32*view.zoom);if(hit){if(placing){toast('This spot already belongs to a package. Choose an empty shelf.');return;}openPackage(hit.parcel);return;}const p=unproject(sx,sy),x=Math.round(p.x),y=Math.round(p.y);if(placing){chooseSpot(x,y);}else if(isShelf(x,y)){toast('An empty shelf. Make a package and leave something here.');}}
function chooseSpot(x,y){if(!isShelf(x,y)){toast('That’s an aisle. Choose a shelf beside it.');return;}if(parcels.has(`${x},${y}`)){toast('There’s already a package here. Pick another spot.');return;}selectedSpot={x,y};$('spotText').textContent=spotName(x,y,view.level);$('placeCard').hidden=false;needsRender=true;}
on('zoomIn','click',()=>{view.zoom=Math.min(1.8,view.zoom+.15);needsRender=true;scheduleLoad();});on('zoomOut','click',()=>{view.zoom=Math.max(.7,view.zoom-.15);needsRender=true;scheduleLoad();});on('homeBtn','click',()=>jumpTo(12,12));on('level','change',()=>{view.level=Number($('level').value);selectedSpot=null;parcels.clear();$('placeCard').hidden=true;needsRender=true;loadPackages();});on('refreshBtn','click',loadPackages);
function jumpTo(x,y){view.x=Math.max(0,Math.min(239,x));view.y=Math.max(0,Math.min(239,y));selectedSpot=null;$('placeCard').hidden=true;needsRender=true;loadPackages();}
on('jumpBtn','click',()=>{$('jumpX').value=Math.round(view.x)+1;$('jumpY').value=Math.round(view.y)+1;$('accessibleSpot').hidden=true;$('navigator').showModal();});on('closeJump','click',()=>$('navigator').close());on('goJump','click',()=>{const x=Number($('jumpX').value)-1,y=Number($('jumpY').value)-1;if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=SIZE||y>=SIZE){toast('Choose aisle and bay numbers from 1 to 240.');return;}jumpTo(x,y);if(placing&&isShelf(x,y)){$('navSpot').textContent=spotName(x,y,view.level);$('accessibleSpot').hidden=false;}else $('navigator').close();});on('navPlace','click',()=>{chooseSpot(Math.round(view.x),Math.round(view.y));$('navigator').close();});on('randomJump','click',()=>{const x=Math.floor(Math.random()*240),y=Math.floor(Math.random()*240);jumpTo(x,y);$('navigator').close();toast('A new corner of the warehouse.');});
async function postage(p){const time=Date.now(),s=JSON.stringify(p)+'|'+time+'|';for(let nonce=0;nonce<10000000;nonce++){const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s+nonce)));if(hash[0]===0&&hash[1]<16)return {time,nonce};if(nonce%100===0)await new Promise(r=>setTimeout(r,0));if(Date.now()-time>240000)throw new Error('The postage check timed out. Try again.');}throw new Error('Could not prepare postage. Try again.');}
let submitting=false;
on('confirmPlace','click',async()=>{if(submitting||!selectedSpot)return;submitting=true;$('confirmPlace').disabled=true;$('confirmPlace').textContent='Adding postage…';const p={...draft,x:selectedSpot.x,y:selectedSpot.y,level:view.level};try{const proof=await postage(p);$('confirmPlace').textContent='Placing…';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);let r;try{r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({package:p,proof}),signal:controller.signal});}finally{clearTimeout(timer);}const result=await r.json();if(!r.ok)throw new Error(result.error||'Could not leave this package.');parcels.set(`${p.x},${p.y}`,result.package);placing=false;selectedSpot=null;$('placementBanner').hidden=true;$('placeCard').hidden=true;$('hint').textContent='Drag to wander · Tap a parcel to peek inside';draft=emptyDraft();pixels.fill(0);hasPhoto=false;for(const key of ['title','sender','recipient','message','caption'])$(key).value='';selectedMark=-1;storeDraft();paintBits($('pixelCanvas'),pixels,128);renderEditor();needsRender=true;toast('Your package has a place in the world.');loadPackages();openPackage(result.package);}catch(e){toast(e.name==='AbortError'?'The connection timed out. Refresh these shelves before trying again.':e.message);loadPackages();}finally{submitting=false;$('confirmPlace').disabled=false;$('confirmPlace').textContent='Leave it here →';}});
let reading=false;
async function openPackage(p){if(reading)return;reading=true;try{if(p.message===undefined){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);let r;try{r=await fetch(API+'?id='+encodeURIComponent(p.id),{signal:controller.signal});}finally{clearTimeout(timer);}const result=await r.json();if(!r.ok)throw new Error(result.error||'Could not open that package.');p=result.package;}readerPackage=p;$('readSpot').textContent=spotName(p.x,p.y,p.level).toUpperCase();$('readTitle').textContent=p.title;$('readFrom').textContent='FROM '+(p.sender||'A STRANGER');$('readTo').textContent='TO '+(p.recipient||'WHOEVER FINDS THIS');$('readMessage').textContent=p.message||'A picture, with no words needed.';$('readDate').textContent='Left here '+new Date(p.created).toLocaleDateString(undefined,{day:'numeric',month:'long',year:'numeric'});$('readPolaroid').hidden=!p.photo;if(p.photo)paintBits($('readImage'),fromHex(p.photo),128);$('readCaption').textContent=p.caption;drawLabel($('readLabel'),p);$('reader').showModal();}catch(e){toast(e.name==='AbortError'?'The package took too long to open. Try again.':e.message);}finally{reading=false;}}
function historyReplace(){historyApi.replaceState({},'',location.pathname);}
const historyApi=window.history;
on('closeReader','click',()=>$('reader').close());$('reader').addEventListener('close',()=>{readerPackage=null;historyReplace();});on('copyLink','click',async()=>{if(!readerPackage)return;const p=readerPackage,url=new URL(location.href);url.search=new URLSearchParams({p:p.id,x:p.x,y:p.y,l:p.level}).toString();try{await navigator.clipboard.writeText(url.href);toast('Package link copied.');}catch{window.prompt('Copy this package link:',url.href);}});
function renderList(){const c=$('listContent');c.replaceChildren();if(!parcels.size){const p=document.createElement('p');p.className='muted';p.style.marginTop='25px';p.textContent='No packages in this corner yet. Leave the first one, or explore another aisle.';c.append(p);return;}[...parcels.values()].sort((a,b)=>b.created-a.created).forEach(p=>{const b=document.createElement('button');b.className='list-item';const title=document.createElement('strong');title.textContent=p.title;const spot=document.createElement('span');spot.textContent=spotName(p.x,p.y,p.level);b.append(title,spot);b.addEventListener('click',()=>{jumpTo(p.x,p.y);openPackage(p);});c.append(b);});}on('listBtn','click',()=>{$('listPanel').hidden=!$('listPanel').hidden;renderList();});on('closeList','click',()=>$('listPanel').hidden=true);
on('aboutBtn','click',()=>$('about').showModal());on('closeAbout','click',()=>$('about').close());on('startMaking','click',()=>{$('about').close();openComposer();});
for(const id of ['reader','about','navigator'])$(id).addEventListener('click',e=>{if(e.target!==$(id))return;const r=$(id).getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$(id).close();});
const query=new URLSearchParams(location.search);if(query.has('p')){view.x=Math.max(0,Math.min(239,Number(query.get('x'))||0));view.y=Math.max(0,Math.min(239,Number(query.get('y'))||0));view.level=Math.max(0,Math.min(3,Number(query.get('l'))||0));$('level').value=view.level;}
paintBits($('pixelCanvas'),pixels,128);paintBits($('stickerCanvas'),stickerBits,32);renderEditor();resize();setInterval(()=>{if(!document.hidden&&!submitting)loadPackages();},15000);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();else loadPackages();});window.addEventListener('beforeunload',stopCamera);
