export const COLORS=['#bb834e','#ad6654','#788b70','#d7ba75','#658991','#80748d'];
export const SIZE=240;
export const isShelf=(x,y)=>x>=0&&y>=0&&x<SIZE&&y<SIZE&&x%6!==5&&y%8!==7;
export function toHex(bits){let s='';for(let i=0;i<bits.length;i+=4)s+=((bits[i]<<3)|(bits[i+1]<<2)|(bits[i+2]<<1)|bits[i+3]).toString(16);return s;}
export function fromHex(hex,size=128){const bits=new Uint8Array(size*size);if(!hex)return bits;for(let i=0;i<hex.length;i++){const n=parseInt(hex[i],16);for(let k=0;k<4;k++)bits[i*4+k]=(n>>(3-k))&1;}return bits;}
export function thresholdPixels(rgba,size,threshold,dither=true){const luminance=new Float32Array(size*size),bits=new Uint8Array(size*size);for(let i=0;i<luminance.length;i++){const a=rgba[i*4+3]/255;luminance[i]=(rgba[i*4]*.299+rgba[i*4+1]*.587+rgba[i*4+2]*.114)*a+255*(1-a);}for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=y*size+x,v=luminance[i],out=v<threshold?0:255;bits[i]=out===0?1:0;if(dither){const error=v-out;if(x+1<size)luminance[i+1]+=error*7/16;if(y+1<size){if(x>0)luminance[i+size-1]+=error*3/16;luminance[i+size]+=error*5/16;if(x+1<size)luminance[i+size+1]+=error/16;}}}return bits;}
export function paintBits(canvas,bits,size){const c=canvas.getContext('2d');const data=c.createImageData(size,size);for(let i=0;i<size*size;i++){const value=bits[i]?27:255;data.data[i*4]=value;data.data[i*4+1]=value;data.data[i*4+2]=value;data.data[i*4+3]=255;}c.putImageData(data,0,0);}
export function worldToIso(x,y){return {x:(x-y)*32,y:(x+y)*16};}
export function isoToWorld(x,y){return {x:x/64+y/32,y:y/32-x/64};}
export const spotName=(x,y,l)=>`Aisle ${String(x+1).padStart(3,'0')} · Bay ${String(y+1).padStart(3,'0')} · Shelf ${l+1}`;
export function drawLabel(canvas,p,selected=-1){const c=canvas.getContext('2d');c.clearRect(0,0,360,220);c.fillStyle='#faf8ef';c.fillRect(0,0,360,220);c.strokeStyle='#c8c3b4';c.lineWidth=1;c.strokeRect(10,10,340,200);c.fillStyle='#27261f';c.font='9px monospace';c.fillText('PACKAGE / AN OPEN ARCHIVE',22,28);c.fillText('HANDLE WITH CURIOSITY',214,28);c.beginPath();c.moveTo(22,38);c.lineTo(338,38);c.stroke();c.font='bold 20px sans-serif';c.fillText((p.title||'Something worth keeping').slice(0,30),22,68,312);c.font='10px monospace';c.fillText('TO',22,94);c.font='16px sans-serif';c.fillText(p.recipient||'Whoever finds this',22,115,300);c.font='9px monospace';c.fillText('FROM  '+(p.sender||'A stranger'),22,147,310);c.fillText('NO RUSH. NO RETURN ADDRESS.',22,191);let x=233;for(let i=0;i<38;i++){const w=i%3===0?3:1;c.fillRect(x,163,w,30);x+=w+1;}c.font='7px monospace';c.fillText('SMALL THINGS / SOMEWHERE',228,203);
(p.decorations||[]).forEach((d,i)=>{c.save();c.translate(d.x,d.y);c.rotate(d.rotation*Math.PI/180);c.fillStyle=d.color;c.strokeStyle=d.color;c.textAlign='center';if(d.type==='stamp'){c.lineWidth=1.8;c.beginPath();c.arc(0,0,36,0,Math.PI*2);c.stroke();c.beginPath();c.arc(0,0,31,0,Math.PI*2);c.stroke();c.font='bold 10px monospace';const words=d.text.split(' ');const mid=Math.ceil(words.length/2);c.fillText(words.slice(0,mid).join(' '),0,-2,57);c.fillText(words.slice(mid).join(' '),0,12,57);c.font='8px monospace';c.fillText('✦  PACKAGE  ✦',0,-18,53);c.fillText('2026',0,25);}else if(d.type==='text'){c.font='bold 16px monospace';c.fillText(d.text,0,6,100);}else if(d.type==='drawing'){c.fillStyle='#fffdf7';c.fillRect(-25,-25,50,50);const b=fromHex(d.bitmap,32);c.fillStyle=d.color;for(let j=0;j<1024;j++)if(b[j])c.fillRect(-22+(j%32)*1.375,-22+Math.floor(j/32)*1.375,1.4,1.4);}else{c.fillStyle='#fffdf7';c.beginPath();for(let j=0;j<24;j++){const a=j*Math.PI/12,r=j%2?24:27;if(j===0)c.moveTo(Math.cos(a)*r,Math.sin(a)*r);else c.lineTo(Math.cos(a)*r,Math.sin(a)*r);}c.closePath();c.fill();c.fillStyle=d.color;c.font='32px sans-serif';c.fillText(d.text,0,11);}if(i===selected){c.strokeStyle='#628698';c.lineWidth=1;c.setLineDash([3,3]);const half=d.type==='stamp'?40:d.type==='text'?53:29;c.strokeRect(-half,-half,half*2,half*2);}c.restore();});}
